### ISSUE TITLE
Error message when redirected to /users after creating account

### ISSUE THREAD

**Issue by torbjoks** [alex2702/tdt4242-shop#5]
Launchy::CommandNotFoundError in Devise::RegistrationsController#create

Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new

**Comment by alex2702** [comment]
Could you check if this problem persists?
