### ISSUE TITLE
Error when registering new customer account

### ISSUE THREAD

**Issue by torbjoks** [alex2702/tdt4242-shop#7]
This happens when ran locally, and I try to create a new user account, check if it is still an issue in the tool chain.

`ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
    
1: Welcome <%= @email %>!\n
    
2: You can confirm your account email through the link below:\n
    
3: <%= confirmation_url(@resource, confirmation_token: @token) %>`

**Comment by alex2702** [comment]
This is probably due to missing environment variables on you local environment. I tried to remove the need for them but not sure if I got them all.
In any case, it shouldn't be an issue in production.
