### ISSUE TITLE
Error when trying to access order management

### ISSUE THREAD

**Issue by torbjoks** [alex2702/tdt4242-shop#8]
This happens when ran locally as and I try to access the order management.

SyntaxError (/home/ec2-user/environment/tdt4242-shop/app/controllers/orders_controller.rb:66: syntax error, unexpected keyword_rescue, expecting keyword_end
        rescue ActiveRecord::ActiveRecordErr
              ^
/home/ec2-user/environment/tdt4242-shop/app/controllers/orders_controller.rb:66: syntax error, unexpected =>
veRecord::ActiveRecordError => e
                              ^
/home/ec2-user/environment/tdt4242-shop/app/controllers/orders_controller.rb:118: syntax error, unexpected keyword_end, expecting end-of-input):
  
app/controllers/orders_controller.rb:66: syntax error, unexpected keyword_rescue, expecting keyword_end
app/controllers/orders_controller.rb:66: syntax error, unexpected =>
app/controllers/orders_controller.rb:118: syntax error, unexpected keyword_end, expecting end-of-input

**Comment by alex2702** [comment]
Not sure where this is coming from but I added another explicit `begin` statement. May be redundant but may fix it, please try as I can't reproduce it.

**Comment by torbjoks** [comment]
I no longer get this error.

**Comment by torbjoks** [comment]
I no longer get this error.
